forward_position:
- 1.6109
- -1.1091
- 0.3067
leg_joints:
- r_hip_yaw
- r_hip_roll
- r_hip_pitch
- r_knee
- r_ankle_pitch
- r_ankle_roll
safety_position:
- 1.6509
- -1.0573
- 0.3067
speed_control_joints:
- r_hip_pitch
- r_knee
- r_ankle_pitch
stop_position:
- 1.6463
- -1.1887
- 0.2094
