# axis ids
joypad_axis_steering: 0
joypad_axis_head_pan: 2
joypad_axis_head_tilt: 3

# button ids
joypad_button_forward: 1
joypad_button_all_stop: 2
joypad_button_steering_sensitivity_plus: 7
joypad_button_steering_sensitivity_minus: 6
joypad_button_head_sensitivity_plus: 5
joypad_button_head_sensitivity_minus: 4
joypad_button_mode_to_default: 11

# correction factors for axis (-1: invert direction)
steering_correction_factor: -1.0
head_pan_correction_factor: 1.0
head_tilt_correction_factor: -1.0
