# axis ids
joypad_axis_steering: 3
joypad_axis_head_pan: 0
joypad_axis_head_tilt: 2

# button ids
joypad_button_forward: 0
joypad_button_all_stop: 1
joypad_button_steering_sensitivity_plus: -1
joypad_button_steering_sensitivity_minus: -1
joypad_button_head_sensitivity_plus: -1
joypad_button_head_sensitivity_minus: -1
joypad_button_mode_to_default: 10

# correction factors for axis (-1: invert direction)
steering_correction_factor: 1
head_pan_correction_factor: 1
head_tilt_correction_factor: 1
