forward_position:
- 1.5898
- -1.0233
- 0.3579
leg_joints:
- r_hip_yaw
- r_hip_roll
- r_hip_pitch
- r_knee
- r_ankle_pitch
- r_ankle_roll
safety_position:
- 1.6733
- -1.0515
- 0.3593
speed_control_joints:
- r_hip_pitch
- r_knee
- r_ankle_pitch
stop_position:
- 1.6237
- -1.0923
- 0.3002
