forward_position:
- -1.6
- 1.4
- 0.27
- 0.0
- 0.0
- 0.0
leg_joints:
- l_leg_hpz
- l_leg_hpx
- l_leg_hpy
- l_leg_kny
- l_leg_aky
- l_leg_akx
safety_position:
- -1.6
- 1.4
- -0.5
- 0.0
- 0.0
- 0.0
speed_control_joints:
- l_leg_hpy
- l_leg_kny
- l_leg_aky
- l_leg_hpz
- l_leg_hpx
- l_leg_akx
stop_position:
- -1.6
- 1.4
- -0.15
- 0.0
- 0.0
- 0.0
