steering_controller_topic: '/thor_mang/left_arm_traj_controller/command'
speed_controller_topic: '/thor_mang/right_leg_traj_controller/command'
head_controller_topic: '/thor_mang/head_traj_controller/command'
#speed_controller_topic: '/thor_mang/right_arm_traj_controller/command'
joint_state_topic: '/thor_mang/joint_states'
